# Déclaration des services applicatifs
services:

  # --- Service Base de Données (MariaDB) ---
  db:
    image: mariadb:10.11
    container_name: wp_mariadb
    restart: always
    environment:
      # Mot de passe administrateur MariaDB (root)
      MYSQL_ROOT_PASSWORD: secret_root_pass
      # Base de données créée à l'initialisation
      MYSQL_DATABASE: wordpress_db
      # Utilisateur applicatif dédié à WordPress
      MYSQL_USER: wp_user
      # Mot de passe de l'utilisateur applicatif
      MYSQL_PASSWORD: secret_user_pass
    volumes:
      # Sauvegarde durable des données SQL hors du conteneur
      - mariadb_data:/var/lib/mysql
    networks:
      # Connexion au réseau interne privé
      - wp_internal_network

  # --- Service Applicatif Web (WordPress) ---
  wordpress:
    # Construit l'image à partir du Dockerfile présent dans le répertoire courant
    build: .
    container_name: wp_core
    restart: always
    depends_on:
      # Attend le démarrage du conteneur 'db' avant de lancer WordPress
      - db
    ports:
      # Mappe le port public 8080 de la VM sur le port 80 HTTP interne du conteneur
      - "8080:80"
    environment:
      # Résolution DNS Docker : 'db' pointe directement sur le conteneur MariaDB
      WORDPRESS_DB_HOST: db:3306
      # Nom de la base de données ciblée
      WORDPRESS_DB_NAME: wordpress_db
      # Identifiants de connexion
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: secret_user_pass
    volumes:
      # Persistance des médias, thèmes et plugins WordPress
      - wp_files:/var/www/html
    networks:
      # Partage le même réseau que la base de données
      - wp_internal_network

# Déclaration des volumes pour éviter toute perte de données
volumes:
  mariadb_data:
  wp_files:

# Réseau Docker isolé dédié à l'application
networks:
  wp_internal_network:
    driver: bridge
